//Branch Model
export const GET_PLACES = "GET_PLACES";

export const GET_PLACES_COUNT = "GET_PLACES_COUNT";

export const GET_PLACE_FROM_ORG = "GET_PLACE_FROM_ORG";
export const GET_PLACE_FROM_BRA = "GET_PLACE_FROM_BRA";
export const GET_PLACE_FROM_GEO = "GET_PLACE_FROM_GEO";

export const GET_LATEST_ORG_IMPORT = "GET_LATEST_ORG_IMPORT";
export const GET_LATEST_BRA_IMPORT = "GET_LATEST_BRA_IMPORT";
export const GET_LATEST_GEO_IMPORT = "GET_LATEST_GEO_IMPORT";

export const GET_PLACE = "GET_PLACE";
export const EDIT_PLACE = "EDIT_PLACE";
export const DELETE_PLACE = "DELETE_PLACE";

//Partner Model
export const GET_PARTNERS = "GET_PARTNERS";
export const GET_PARTNER = "GET_PARTNER";
